version: '3.9'
services:
  authenticator:
    image: "shopify_installer:production"
    container_name: "shopify_installer"
    build: "."
    ports:
      - "10001:8000"
    environment:
      - DB_NAME=shopify_installation
      - DB_USER=shopify_installer_service
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - REDIS_HOST=redis_install
      - REDIS_PORT=6379
    networks:
      - proxynet
      - redis_network
  redis:
    container_name: redis_install
    image: redis
    restart: always
    ports:
      - "10003:6379"
    networks:
      - redis_network

networks:
  proxynet:
    name: ozia_backend
  redis_network:
