name: "Deploy Shopify Installer on test server"

on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Publish on the test server"
    steps:
      - uses: actions/checkout@v4
      - name: Create a remote docker context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST }}
          context_name: "remote"
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}
      - name: Deploy Shopify Installer on created context
        env:
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          DB_HOST: ${{ secrets.TEST_DB_HOST }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
        run: |
          docker --context remote compose up --build -d

